### ISSUE TITLE
MyFT Duplicate links

### ISSUE THREAD

**Issue by lc512k** [Financial-Times/next-a11y#11]
https://github.com/Financial-Times/next-myft-page/issues/1033

**Comment by lc512k** [comment]
@keirog @andygout this one seems completed. Good to close?

**Comment by andygout** [comment]
We've addressed `Actions and more information` but not the repetition of `Topics included`.

I'd imagine it's not as simple as removing for screen-readers (as we did for `Actions…`) given we want to indicate that the list provided is not necessarily the full list (it will read as, e.g. `list, 4 items`), so requires consideration.
