### ISSUE TITLE
Make sure Read More (and others) doesn't break article flow

### ISSUE THREAD

**Issue by lc512k** [Financial-Times/next-a11y#12]
When read with a screen reader (jaws) article is broken up by Read Me and other asides we’ve stuck along the way. Light signup breaks the flow too.

DAC-USER-SRJAWS-T2-04

**Comment by lc512k** [comment]
@keirog Forgot to add we can reproduce this in VO by doing `ctrl+alt+A` so it reads out the text and we can hear it read out "related article" in the middle of reading the article itself 

(putting the focus on something right before "read article" helps, so it doesn't have to read out the entire thing every time we want to test)

<img width="773" alt="screen shot 2017-01-13 at 09 44 33" src="https://cloud.githubusercontent.com/assets/3425322/21925334/eb78d83c-d974-11e6-9506-cb98fefc4447.png">

**Comment by lc512k** [comment]
Ideally all those "related article" boxes would come after all the article text in the markup, rather than be sandwiched between the `<p>`s. If that were the case, SRs would just read them in order.

Less ideal, if we can't move the markup to the bottom? Moving them till after all the `<p>`s in the tab order, but we'd still need to make sure they can be tabbed to, and using tabindex other than 0 or -1 isn't recommended, so I wouldn't be immediately sure how to solve things down this route...

</ramble>

**Comment by keirog** [comment]
I totally feel that frustration too, regarding the markup. Taking control of tab order would make things worse as it’s bound to go wrong.

I think the only thing we can do right now is try to make it clearer when the screenreader user is being taken away from the content, and also when they’re brought back to it. I’ll add some extra information to the related article areas and see if that reads better.

**Comment by lc512k** [comment]
I wonder what the lesser of two evils is here: (politely) interrupting the flow or just hiding the boxes altogether from screen readers... it can be 2 or 3 of them per article, right? Plus light signup and maybe other things?

~~I'm tempted by `tabindex=9999` right now 🙈~~

**Comment by lc512k** [comment]
Yeah, I agree, lets hide them for now. One for the 'things to ask DAC' doc?
