### ISSUE TITLE
Add .visually-hidden class to n-ui, available everywhere

### ISSUE THREAD

**Issue by lc512k** [Financial-Times/next-a11y#20]
next-a11y and next-signup have their own visually-hidden, n-barriers and product-selector have u-visually-hidden. Update all to use a global one. Create a global one if one doesn't exist yet. We need it available everywhere

**Comment by i-like-robots** [comment]
This class already exists in n-ui and is fairly widely used: https://github.com/Financial-Times/n-ui/blob/40ad885c2351761a0c16f623b0b6e415d6019277/utils/main.scss#L35-L45

**Comment by lc512k** [comment]
Fab, thanks @i-like-robots !

**Comment by lc512k** [comment]
https://github.com/Financial-Times/next-signup/pull/903
https://github.com/Financial-Times/next-product-selector/pull/242
