### ISSUE TITLE
target="_blank"

### ISSUE THREAD

**Issue by lc512k** [Financial-Times/next-a11y#23]
Issue ID: DAC-USER-SRJAWS-T2-02
Article (--and a11y survey link-- and anywhere that has target _blank)
Links that open in a new window should announce it in the label as ‘Share on Facebook, opens in a new window’, links within articles too

One option is below. Look up best practices for this.

```
<a href="..." target="_blank">some link <span class="visually-hidden">opens in a new window</span></a>
```

**Comment by keirog** [comment]
Related (but about security with `_blank`): https://mathiasbynens.github.io/rel-noopener/
