### ISSUE TITLE
Front Page Headings

### ISSUE THREAD

**Issue by lc512k** [Financial-Times/next-a11y#29]
@keirog All that remains is really to do a sanity check on the journey's DAC is going to look at (front page, article, barriers, signup, stream) and make sure headings don't break the rules. We can probably look at further improvements later

~~DAC-USER-SRJAWS-T1-03
Video is H2 but the following heading is H4. Gift guide is H2 and the next item H6.~~
~Video-scroller__title was an example of H2 followed by H4~

~~DAC-USER-SRJAWS-T2-03~~
~~DAC_TECH_Headings_Issue~~
~~Duplicate headings in the front page (Read More). Need to be made unique and more descriptive~~

**Comment by keirog** [comment]
👍  Ok I'll do a run through today

**Comment by keirog** [comment]
Made an [issue for checking general heading hierarchies](https://github.com/Financial-Times/next-a11y/issues/60), so closing this now
