### ISSUE TITLE
Video Carousel Focus

### ISSUE THREAD

**Issue by lc512k** [Financial-Times/next-a11y#6]
Ensure Video carousel on front page can be used with only the keyboard. Check video everywhere, including video.ft.com

- ~Close video button can't be reached by keyboard / screen readers (DAC-USER-SRVO-T1-03)~
- ~it's possible to move off the video player and select other videos breaking the UI (Media_Issue_1 and Media_Issue_2)~

Other related issues:
~~DAC_TECH_Navigation_Issue~~
DAC-USER-SRJAWS-T1-10: Jaws. Make sure it makes sense in screen reader
~~DAC-USER-KO-T1-01~~
~DAC-USER-KO-T10-07: Skip ad~
~~DAC-USER-SRJAWS-T1-11~~~

Make sure buttons aren't all labeled "Play button"

**Comment by keirog** [comment]
Closing this issue; have added https://github.com/Financial-Times/next-a11y/issues/62 and https://github.com/Financial-Times/next-a11y/issues/63 for later
