### ISSUE TITLE
Make sure heading hierarchy is sequentional across main DAC journeys

### ISSUE THREAD

**Issue by keirog** [Financial-Times/next-a11y#60]
Check front page, article, barriers, signup, stream for any dodgy heading numbers (e.g. `h1 > h3 > h4`)

- [x] front page
- [x] article
- [x] barriers
- [x] signup
- [x] stream

**Comment by lc512k** [comment]
Just checked signup, looks good. Thanks for nuking all the other ones, Keith! 🙌
