### ISSUE TITLE
Heading Sanity Check 

### ISSUE THREAD

**Issue by lc512k** [Financial-Times/next-a11y#80]
- [ ] Sanity check on our main pages for heading structure
    - [ ] Single H1 in all
    - [ ] Rest of headings are sequential
- [x] Building a commit hook OR extending pa11y to check the above automatically on every build
    - [x] The errors app (next-errors) is a good place to experiment: it's small and it's got bad headings. https://www.ft.com/errors/page/404 github.com/Financial-Times/next-errors

**Comment by Lily2point0** [comment]
Waiting for `pa11y` PR to be merged > https://github.com/pa11y/pa11y/pull/253

**Comment by Lily2point0** [comment]
`pa11y 4.9.0` has been deployed
To check headings:
- ensure the repo is using the latest version
- add ```js
rules: [
        'Principle1.Guideline1_3.1_3_1_AAA'
    ]
```
to the config `.pallyci.js` in relevant repos

**Comment by lc512k** [comment]
Awesome!! 🎉 
Thanks @Lily2point0 !
