### ISSUE TITLE
Implement more-prominent focused states (for keyboard users)

### ISSUE THREAD

**Issue by keirog** [Financial-Times/next-a11y#87]
On first(?) keyboard tab, add BEM modifier to `<html>` to activate an arrow when elements are focused

**Comment by keirog** [comment]
Have added a `a11yKeyboardFocus` flag for this

**Comment by lc512k** [comment]
I'll pick your brains on this soon, I love it

**Comment by keirog** [comment]
Just to document it here, there’s now a `has-tabbed` class that can be added to the `<html>`/`<body>`, which triggers a claret box-shadow around focussed `<a>`s and other focusable things.

Rationale:
  - We need to make our focus states more prominent
  - We can hide these prominent states from people who tend to complain about such things, and try to show it only to people who may find it useful (obviously there’s no silver bullet solution for that, but we can try) 😁

To do:
- [ ] Add some client-side JS to trigger the `has-tabbed` class when someone has used the tab key at least once:
  - [ ] If not yet triggered, don’t trigger if a first tab happens from a form control (apart from button)?
    (This’ll hopefully lower the chances of a big-outline-averse person seeing it, as lots more people use the tab key when filling out forms) 
  - [ ] Progressively enhanceeee: make this work for `non-js` by default, then for older but ES5-capable browsers (so using the `js` CSS hook rather than `enhanced`)
